# Generated by Django 5.0.6 on 2024-06-26 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='song',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='first_name',
            new_name='artist_name',
        ),
        migrations.RemoveField(
            model_name='album',
            name='songlist',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='last_name',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
